name: SubKT Mux and Upload

on:
  workflow_dispatch:
    inputs:
      mux_numbers:
        description: 'Specific mux numbers to run (comma-separated, e.g. "01,NCOP1")'
        required: false
        type: string
      run_all:
        description: 'Run all mux tasks'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '16'
        distribution: 'temurin' 
        cache: 'gradle' 

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master' }}
        cache-overwrite-existing: true
        generate-job-summary: true
   
    - name: Setup Rclone
      uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE }}

    - name: Install mkvtoolnix
      run: |
        sudo apt-get update
        sudo apt-get install -y mkvtoolnix

    - name: Mount raws folder
      run: |
        mkdir -p ./raws
        rclone mount raws:DSNP ./raws --daemon --vfs-cache-mode full --allow-non-empty
        sleep 5
        ls -la ./raws

    - name: Extract mux task numbers
      id: extract-tasks
      run: |
        # Run gradlew tasks and extract mux task numbers
        TASK_OUTPUT=$(./gradlew tasks --all)
        MUX_TASKS=$(echo "$TASK_OUTPUT" | grep -oE 'mux\.[^.]+' | sed 's/mux\.//')
        
        # Format as space-separated list for Gradle command
        MUX_TASKS_ALL=$(echo "$MUX_TASKS" | sed 's/^/mux./' | tr '\n' ' ')
        
        echo "mux_tasks_all=$MUX_TASKS_ALL" >> $GITHUB_OUTPUT

    - name: Run gradlew
      run: |
        ls ./ 
        ls raws/
        ./gradlew

    - name: Run specified mux tasks
      if: ${{ inputs.mux_numbers != '' }}
      run: |
        TASKS=$(echo "${{ inputs.mux_numbers }}" | tr ',' '\n' | sed 's/^/mux./' | tr '\n' ' ')
        echo "Running specified tasks: $TASKS"
        ./gradlew $TASKS
        
    - name: Run all mux tasks
      if: ${{ inputs.run_all == 'true' }}
      run: |
        TASKS="${{ steps.extract-tasks.outputs.mux_tasks_all }}"
        echo "Running all tasks: $TASKS"
        ./gradlew $TASKS

    - name: Upload to Drive.
      run: |
        rclone copy ./muxdir muxout: -P

    - name: Unmount rclone folders
      if: always()
      run: |
        fusermount -u ./raws || true